version: '3'

services:
  spark-notebook:
    container_name: spark-notebook
    image: unigap/spark:3.5
    networks:
      - streaming-network
    volumes:
      - spark_data:/data
      - spark_lib:/opt/bitnami/spark/.ivy2
      - ./:/spark
    environment:
      - PYSPARK_PYTHON=python3
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8888:8888' #jupyter
      - '4041:4040' #spark-job
    command: >
      /bin/bash -c "
      pip install py4j jupyter && 
      cd /spark &&
      jupyter notebook --ip=0.0.0.0 --no-browser --allow-root;
      "
  
networks:
  streaming-network:
    external: true
volumes:
  spark_data:
    external: true
  spark_lib:
    external: true